### ISSUE TITLE
Bug filtre enderio avec l'oxygène de NuclearCraft

### ISSUE THREAD

**Issue by acot-server** [Axelandre42/Insomnia#12]
**Description du bug**
L'oxygène de NuclearCraft n'est pas reconnue pas les fluid filter d'enderio

**Reproduire le bug**
A la sortie d'un electrolyzer à eau de NuclearCraft, conserver le Deuterium et void l'hydrogène et l'oxygène. Le deuterium et l'hydrogène respectent bien les filtres mais l'Oxygène reste bloquer dans l'electrolyzer.

**Ce qui aurait du ce passer**
L'Oxygène et l'hydrogène doivent être void et le deuterium est stocker.
Seul l'oxygène reste bloquer dans l'electrolyzer.

**Captures d'écran**

![2019-04-18_17 43 12](https://user-images.githubusercontent.com/49619596/56373614-a2f58700-6201-11e9-9ac9-78bc8e6574f8.png)

**Comment by Annwan** [comment]
Cela est vrai avec tout tuyau et filtre
