### ISSUE TITLE
craft problème

### ISSUE THREAD

**Issue by Loric0** [Axelandre42/Insomnia#9]
**Description du bug**
le craft
Une description claire et concise du bug.
les 2 craft du forester's manual
**Reproduire le bug**
c'est le craft
Ce qui nous permettrait de reproduire le bug (pour le comprendre):
1. Faire Machin
2. Aller dans truc
3. '...'

**Ce qui aurait du ce passer**
le craft
Une description claire et concise de ce que vous pensiez qui allait se passer (et qui n'a vraisemblablement pas eu lieu ainsi)

**Captures d'écran**
???
Les captures d'écran ça aide, vraiment

**Crash Report**
nop
Si il s'agit d'un crash, merci de lier le report à l'issue (glisser-déposer le fichier `crash_report.txt`)
**Autres remarques**
rien
Précisions suplémentaires sur le bug
rien

**Comment by alwaeles** [comment]
L'issue est invalide car on y comprends rien... Mais pour la peine, @galyfray s'en occupe...
